# -*- coding: utf-8 -*-
"""Apple stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNUmZ3QCoQH1aO2uZqoaXskczRv4bjmO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("/content/AAPL.xlsx")

df.head()

df.tail()

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

print(df[["Date"]].head(10))

df["Daily Price Change"] = df["Close"].diff()

df["Daily Percentage Change"] = df["Close"].pct_change() * 100

print(df.head(10))

print("\nStock Price Analysis:")
print("Highest Price:", df["High"].max())
print("Lowest Price:", df["Low"].min())
print("Average Closing Price:", df["Close"].mean())

print("\nDaily Price Change:")
print(df[["Date", "Close", "Daily Price Change", "Daily Percentage Change"]])

plt.figure(figsize=(10, 5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("AAPL Stock Price Analysis")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()